[build]
  publish = "public"

[[redirects]]
  from   = "/handles.json"
  to     = "/handles.json"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  force  = true
